name: 'Set Nuget PackageVersion'
description: 'Set PackageVersion in csproj files'
inputs:
  version:
    description: 'Version to set'
    required: true
    default: '0'
runs:
  using: "composite"
  steps:
    - run: |
        version=${{inputs.version}}
        echo The version is $version
        for i in `find . -type f -iname '*.csproj'`; do sed -i'' -e "s/\(PackageVersion>[0-9]*\.[0-9]*\.[0-9]*\.\)\([0-9]*\)/\1${version}/" $i; done
      shell: bash
