name: 'Set Nuget PackageVersion'
description: 'Set PackageVersion in csproj files'
runs:
  using: "composite"
  steps:
    - run: |
        for f in $(find ${{github.workspace}} -type f -iname "*.csproj"); do sed -i'' -e "s/\(PackageVersion>[0-9]*\.[0-9]*\.[0-9]*\.\)\([0-9]*\)/\1${{github.run_attempt}}}}/" $i; done
        echo "My name is Tuan"
      shell: bash
